services:
  - type: web
    name: brasileirao-g2-proxy
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: API_FUTEBOL_KEY
        sync: false
